<template>
	<div class="todo-item">
		<!-- some bug with input, remove this and make it an svg instead, because it bugs out -->
		<!-- <input
			type="checkbox"
			id="checklist"
			name="checklist"
			@click="toggleDone"
		/> -->
		<div class="completed-container" @click.stop="toggleDone">
			<font-awesome-icon
				v-if="todo.completed"
				:icon="['fas', 'check-square']"
				class="fcomplete"
			/>
			<!-- empty checkbox -->
			<font-awesome-icon v-else :icon="['far', 'square']" class="fcomplete" />
		</div>

		<!-- <label for="checklist">Checklist</label> -->
		<div
			class="todo-info"
			@click="editTodo"
			:class="{ todoComplete: todo.completed }"
		>
			<h1 :style="{ color: todo.completed ? '#605C5E' : '' }">
				{{ todo.title }}
			</h1>
		</div>
		<button class="favourite-button">
			<span @click="toggleFavourite">
				<font-awesome-icon
					:icon="['fas', 'star']"
					id="favourite"
					:class="{ gold: todo.favourite }"
				/>
			</span>
		</button>
	</div>
	<Transition>
		<TodoEdit
			v-if="isEditing"
			:todo="todo"
			ref="modalRef"
			@close-edit="closeFunc"
		/>
	</Transition>
</template>

<script setup lang="ts">
import { Todo } from "@/class/Todo";
import { onClickOutside } from "@vueuse/core";
import { ref } from "vue";
// import TodoCreator from "./TodoCreator.vue";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import TodoEdit from "./TodoEdit.vue";

let isEditing = ref(false);
let modalRef = ref(null);
// custom directive for focusings.
// const checkFocus = {
// 	mounted(el: HTMLElement) {
// 		el.focus();
// 		onclick;
// 	},
// };

onClickOutside(modalRef, (e) => {
	setTimeout(() => {
		isEditing.value = false;
	}, 0);
	console.log(e);
});

function toggleEditing(editing: boolean) {
	isEditing.value = editing;
}
const props = defineProps({
	todo: {
		type: Todo, // the reason this is not Todo is because when we load from local storage it returns an Objec
		// it would require sterializaer to convert it back to a Todo object, but that is a little too much work..
		required: true,
	},
});

// i see the problem with this approach, this one gets ALL elements with favourte,
// instead of the one i want so it messes up

// var favourite = document.getElementById("favourite");
// favourite?.addEventListener("click", toggleFavourite);
function toggleDone() {
	props.todo.toggleCompleted();
	if (props.todo.completed) {
		var completionSound = new Audio("sounds/completion2.mp3");
		// console.log("completed");
		completionSound.play();
		// completionSound.currentTime = 0; // Start at the beginning
		// completionSound.play();
		// setTimeout(() => {
		// 	completionSound.pause(); // Pause the sound
		// 	completionSound.currentTime = 0; // Reset the time
		// }, 700); // Stop after 500 milliseconds (0.5 seconds)
	}
}

function toggleFavourite() {
	props.todo.toggleFavourite();
	console.log("toggleFavourite");
	console.log(props.todo.favourite);
	// console.log(favourite);
}

// if (props.todo.favourite) {
// 	favourite.style.color = "gold";
// }

function editTodo() {
	// prob show a popup or something
	console.log("editTodo");
	isEditing.value = true;
}

// console.log("Logging prop[s into" + props);
</script>

<style scoped>
/* testing for favourite */
/* #favourite {
	color: gray;
} */
.v-enter-active,
.v-leave-active {
	transition: opacity 0.3s ease;
}

.todoComplete {
	text-decoration: line-through;
	/* color: gray !important; */
}

.v-enter-from,
.v-leave-to {
	opacity: 0;
}

/*  */
div {
	background-color: aliceblue;
}
.completed-container {
	width: 5%;
	/* color: inherit; */
	background-color: inherit;
	/* height: 1.5rem; */
	font-size: 3rem;
	display: flex;
	align-items: center;
	justify-content: center;
	margin: 20px;
}
.fcomplete {
	/* color: green; */
	/* width: 20px; */
}
.gold {
	color: gold;
}
/* generated by copilot */
.todo-info {
	display: flex;
	flex-direction: column;
	background-color: inherit;
	justify-content: center;
	align-items: start;
	text-align: left;
	width: 90%;
	/* margin: 20px; */
	margin-left: 40px;
}

.todo-item {
	background-color: #fff;
	border: 1px solid #ddd;
	border-radius: 5px;
	box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
	/* padding: 20px; */
	margin-bottom: 20px;
	margin-right: 40px;
	margin-left: 40px;
	display: flex;
	flex-direction: row;
	justify-content: space-between;
	/* margin: 40px; */
}
.todo-item:hover {
	box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
	background-color: #f0f0f0;
	cursor: pointer;
}

#checklist {
	width: 5%;
	/* height: 1.5rem; */
}

.favourite-button {
	background: none;
	color: gray;
	border: none;
	font-size: 20px;
	cursor: pointer;
	width: 3%;
	margin: 20px;
}

/* .favourite-button:hover {
	color: gold;
} */
/*  */

h1 {
	color: red;
}

p {
	color: blue;
}

p:nth-child(3) {
	color: green;
}

p:nth-child(4) {
	color: purple;
}
</style>
