<template>
	<div class="todo-item">
		<div class="completed-container" @click.stop="toggleDone">
			<font-awesome-icon
				v-if="todo.completed"
				:icon="['fas', 'check-square']"
				class="fcomplete"
			/>
			<!-- empty checkbox -->
			<font-awesome-icon v-else :icon="['far', 'square']" class="fcomplete" />
		</div>

		<!-- <label for="checklist">Checklist</label> -->
		<div
			class="todo-info"
			@click="editTodo"
			:class="{ todoComplete: todo.completed }"
		>
			<p :style="{ color: todo.completed ? '#605C5E' : '' }">
				{{ todo.title }}
			</p>
		</div>
		<button class="favourite-button">
			<span @click="toggleFavourite">
				<font-awesome-icon
					:icon="['fas', 'star']"
					id="favourite"
					:class="{ gold: todo.favourite }"
				/>
			</span>
		</button>
	</div>
	<Transition>
		<TodoEdit
			v-if="isEditing"
			:todo="todo"
			ref="modalRef"
			@close-edit="toggleEditing"
		/>
		<!-- @close-edit="closeFunc" -->
	</Transition>
</template>

<script setup lang="ts">
import { Todo } from "@/class/Todo";
import { onClickOutside } from "@vueuse/core";
import { ref, inject } from "vue";
// import TodoCreator from "./TodoCreator.vue";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import TodoEdit from "./TodoEdit.vue";
import { fireStorage } from "@/utils/fireStorage";

let isEditing = ref(false);
let modalRef = ref(null);
// const util = new fireStorage();
// util.init();
const tutil: fireStorage = inject("fire-storage")!;
// emits
let emit = defineEmits(["toggleFavourite", "toggleDone"]);

// custom directive for focusings.
// const checkFocus = {
// 	mounted(el: HTMLElement) {
// 		el.focus();
// 		onclick;
// 	},
// };

onClickOutside(modalRef, (e) => {
	setTimeout(() => {
		isEditing.value = false;
	}, 0);
	console.log(e);
});

function toggleEditing(editing: boolean) {
	isEditing.value = editing;
}
// const props = defineProps({
// 	todo: {
// 		type: Todo, // the reason this is not Todo is because when we load from local storage it returns an Objec
// 		// it would require sterializaer to convert it back to a Todo object, but that is a little too much work..
// 		required: true,
// 	},
// });
// change it to interface at some point
const props = defineProps({
	todo: {
		type: Object,
		required: true,
	},
});

// i see the problem with this approach, this one gets ALL elements with favourte,
// instead of the one i want so it messes up

// var favourite = document.getElementById("favourite");
// favourite?.addEventListener("click", toggleFavourite);
function toggleDone() {
	// props.todo.toggleCompleted();

	if (!props.todo.completed) {
		// props.todo.completed = true;
		// util.toggleCompleted(props.todo.id, true);

		var completionSound = new Audio("sounds/completion2.mp3");
		// console.log("completed");
		completionSound.play();
		// completionSound.currentTime = 0; // Start at the beginning
		// completionSound.play();
		// setTimeout(() => {
		// 	completionSound.pause(); // Pause the sound
		// 	completionSound.currentTime = 0; // Reset the time
		// }, 700); // Stop after 500 milliseconds (0.5 seconds)
		emit("toggleDone", props.todo.id, true);
	} else {
		emit("toggleDone", props.todo.id, false);
	}
}

function toggleFavourite() {
	console.log("toggleFavourite");
	if (!props.todo.favourite) {
		// emit("toggleFavourite", props.todo.id, true);
		tutil.toggleFavourite(props.todo.id, true);
	} else {
		tutil.toggleFavourite(props.todo.id, false);
		// emit("toggleFavourite", props.todo.id, false);
	}
}

function editTodo() {
	// prob show a popup or something
	console.log("editTodo");
	isEditing.value = true;
}

// console.log("Logging prop[s into" + props);
</script>

<style scoped>
/* testing for favourite */
/* #favourite {
	color: gray;
} */
.v-enter-active,
.v-leave-active {
	transition: opacity 0.3s ease;
}

.todoComplete {
	text-decoration: line-through;
	/* color: gray !important; */
}

.v-enter-from,
.v-leave-to {
	opacity: 0;
}

/*  */
div {
	/* background-color: aliceblue; */
	background-color: #121212;
}
.completed-container {
	width: 5%;
	/* color: inherit; */
	background-color: inherit;
	/* height: 1.5rem; */
	font-size: 3rem;
	display: flex;
	align-items: center;
	justify-content: center;
	margin: 12px;
}
.fcomplete {
	/* color: green; */
	color: #ddd;
	width: 20px;
	/* border: 1px solid white; */
	/* border-radius: 10px; */
	/* width: 20px; */
}
.gold {
	color: gold;
}
/* generated by copilot */
.todo-info {
	display: flex;
	flex-direction: column;
	background-color: inherit;
	justify-content: center;
	align-items: start;
	text-align: left;
	width: 90%;
	/* margin: 20px; */
	margin-left: 40px;
}

.todo-item {
	/* background-color: #fff; */
	border: 1px solid #ddd;
	border-radius: 10px;
	box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
	/* padding: 20px; */
	margin-bottom: 5px;
	margin-right: 40px;
	margin-left: 40px;
	display: flex;
	flex-direction: row;
	justify-content: space-between;
	opacity: 0.9;
	/* margin: 40px; */
}
.todo-item:hover {
	opacity: 0.8;
	box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
	/* background-color: #f0f0f0; */
	cursor: pointer;
}

#checklist {
	width: 5%;
	/* height: 1.5rem; */
}

.favourite-button {
	background: none;
	color: gray;
	border: none;
	font-size: 20px;
	cursor: pointer;
	width: 3%;
	margin: 12px;
}

/* .favourite-button:hover {
	color: gold;
} */
/*  */

h1 {
	color: white;
	opacity: 0.9;
}

p {
	color: white;
	opacity: 0.9;
	/* color: blue; */
	font-size: 1.5rem;
}
@media (max-width: 600px) {
	p {
		font-size: 1rem;
	}
}
</style>
